image: mephux/golang
git:
  path: github.com/criticalstack/brotop
  branch: master
env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin
script:
  - git config --global url.ssh://git@github.com/.insteadOf https://github.com/
  - go get github.com/jteeuwen/go-bindata/...
  - go get github.com/tools/godep
  - make test
notify:
  email:
    recipients:
      - $$EMAIL
  slack:
    username: $$USERNAME
    webhook_url: $$WEBHOOK
    channel: $$CHANNEL
    on_started: false
    on_success: true
    on_failure: true
publish:
  github:
    branch: word
    script:
      - make release
    artifacts:
      - release
    tag: v$(cat brotop.go | grep -oP "Version\s+?\=\s?\"\K.*?(?=\"$|$\)")
    token: $$github_token
    user: criticalstack
    repo: brotop
